### ISSUE TITLE
CREAR LAS HISTORIAS DE USUARIO

### ISSUE THREAD

**Issue by Yhor93** [ramisistemas/Gimnasio#10]

**Comment by Jhosal** [comment]
[HISTORIA DE USUARIOS.docx](https://github.com/ramisistemas/Gimnasio/files/9426700/HISTORIA.DE.USUARIOS.docx)

**Comment by KissianCastro** [comment]
[Historias de usuario_GRUPO 02.docx](https://github.com/ramisistemas/Gimnasio/files/9429497/Historias.de.usuario_GRUPO.02.docx)

**Comment by ramisistemas** [comment]
[HISTORIA.DE.USUARIOS.docx](https://github.com/ramisistemas/Gimnasio/files/9436258/HISTORIA.DE.USUARIOS.docx)
