### ISSUE TITLE
ESTABLECER MAPEO A LA BASE DE DATOS

### ISSUE THREAD

**Issue by Yhor93** [ramisistemas/Gimnasio#11]

**Comment by Yhor93** [comment]
![Image](https://user-images.githubusercontent.com/111392975/186534449-0b775da3-59ca-4d00-a701-9efbbdac7a2f.png)

**Comment by ramisistemas** [comment]
![Image](https://user-images.githubusercontent.com/20059814/186987291-3e662b1f-5127-48d5-9220-f94daec0db76.png)
