### ISSUE TITLE
Repositorios de las entidades restantes

### ISSUE THREAD

**Issue by Yhor93** [ramisistemas/Gimnasio#16]

**Comment by ramisistemas** [comment]
![Image](https://user-images.githubusercontent.com/20059814/188226429-efaa5eaa-c58c-426b-898f-42dc11d3787a.png)



![Image](https://user-images.githubusercontent.com/20059814/187997297-ae8c8a7f-ade2-4c80-9904-50554cdeeb31.png)

**Comment by ramisistemas** [comment]
![Image](https://user-images.githubusercontent.com/20059814/188226042-2158f34a-36dc-4ec4-b4d5-940886807a72.png)
