### ISSUE TITLE
CRUD Entidad Cliente

### ISSUE THREAD

**Issue by Yhor93** [ramisistemas/Gimnasio#25]

**Comment by ramisistemas** [comment]
![Image](https://user-images.githubusercontent.com/20059814/189493998-41204e7e-bc77-4178-8c7c-f3f58fdebd85.png)



![Image](https://user-images.githubusercontent.com/20059814/189471900-fa33ca40-47f1-4887-bbe4-e7613d6c154a.png)



![Image](https://user-images.githubusercontent.com/20059814/189471907-4ad274eb-8478-48ed-a402-e4f393b6fc71.png)



![Image](https://user-images.githubusercontent.com/20059814/189471942-73696308-cc3e-4b33-b4fe-ebf67b09ebd7.png)
