### ISSUE TITLE
Hacer  puebas a la aplicacion web en pro de encontrar error

### ISSUE THREAD

**Issue by Yhor93** [ramisistemas/Gimnasio#52]

**Comment by Jhosal** [comment]
Formulario de Registro:
1. cuando realizo registro deberia salir error en el correo si no llevo el @, ya que significa que esta mal el correo.
2. validar que en la edad y telefono solo se puedan numero, porque coloco letras y no sale error
3.  pienso que la persona pueda registrarse con 1 nombre y 1 apellido, ya que hay personas que tiene un solo apellido
4. validar que en nombres y apellidos sea solo letras, que no se vaya a colocar numeros

formulario rutinas ejercicios:
1. no permitir que el usuario elija el nivel sin que haya tenido la valoracion, que al ingresar aca solo se le habilite el boton de valoracion
2. en la valoracion, se validen los campos de estatura y peso para que sea solo numerico, para que el usuario no ingrese letras o simbolos - ya verifique y no deja pasar, pero deberia salir un mensaje o mejor si se puede por que no se.... deshabilitar las letras..
3. no se como lo vean si un boton de devolver sea bueno.

formulario de consejo nutricional:
1. solo habilitar el boton de valoracion para que se inicie con este...
2. en la valoracion, se validen los campos de estatura y peso para que sea solo numerico, para que el usuario no ingrese letras o simbolos - ya verifique y no deja pasar, pero deberia salir un mensaje..... deshabilitar las letras..


boton Historico y Salir no se realizan nada.... y aveces cuando una se devuelve en la aplicacion y digamos voy a seleccionar concejo nutricionales no lo toma.... 
Salir dejarlo en la pagina de inicio....
