### ISSUE TITLE
Diagrama Modelo de Clase de Entidad

### ISSUE THREAD

**Issue by ramisistemas** [ramisistemas/Gimnasio#8]

**Comment by Yhor93** [comment]
![Image](https://user-images.githubusercontent.com/111392975/185983448-c3304658-9ad6-42e3-b161-a0a9c23426dc.png)

**Comment by Yhor93** [comment]
![Image](https://user-images.githubusercontent.com/111392975/188534633-b47a6621-5bd4-4488-897a-6d1b24a0afd4.png)











archivo actualizado
